### ISSUE TITLE
ISBAT move blocks around with motion in Gutenberg 6.1.1

### ISSUE THREAD

**Issue by bobbingwide** [godaddy/coblocks#668]
**Describe the bug**
With Gutenberg 6.1.1 and CoBlocks 1.1.1 moving blocks becomes a bit of a challenge.

![image](https://user-images.githubusercontent.com/2474435/61284637-46314a80-a7b7-11e9-96e9-5a026f3b4547.png)

**To Reproduce**

1. Update to Gutenberg 6.1.1 and CoBlocks 1.11.1
2. Add a new post
3. Insert 3 blocks: paragraph, more, paragraph 
4. Click on the second paragraph block to move it up.
5. See the More and second paragraph block overlapping.
6. Switch to Code Editor then back to Visual to see it how you'd expect it.

**Screenshots**

**Expected behavior**
Blocks should move correctly.

**Isolating the problem:**
Mark completed items with an [x].

-   [ ] This bug happens with no other plugins activated
-   [ ] This bug happens with a default WordPress theme active
-   [ ] This bug happens **without** the Gutenberg plugin active
-   [x] I can reproduce this bug consistently using the steps above

**WordPress Version**
5.2.2

**Gutenberg Version**
6.1.1. It's fine with 6.0.

**Comment by richtabor** [comment]
I've confirmed the issue and it seems to be attributed to the `withFontSettings` [here](https://github.com/godaddy/coblocks/blob/master/src/extensions/typography/index.js#L81-L128). More info can be found [here](https://github.com/WordPress/gutenberg/blob/5a3c3586024fbb0b9e0276b5e31103ddf83edd52/docs/designers-developers/developers/filters/block-filters.md#editorblocklistblock) about the filter.

**Comment by jrtashjian** [comment]
This may be an issue related to the Gutenberg plugin. An issue submitted to the Gutenberg project recently that I updated with my findings so far while looking into this issue.

**Comment by paranoia1906** [comment]
This issue seems to be resolved with Gutenberg 6.2.0-rc.1

This seems to be the relevant merge.
https://github.com/WordPress/gutenberg/pull/16750

### Movement with Gutenberg 6.1.1
![blockMovementBefore](https://user-images.githubusercontent.com/30462574/62142762-bf469c80-b2a3-11e9-85db-3853903cd076.gif)


### Movement with Gutenberg 6.2.0-rc.1
![blockMovementAfter](https://user-images.githubusercontent.com/30462574/62144248-54e32b80-b2a6-11e9-9371-1df20f761a47.gif)

**Comment by paranoia1906** [comment]
Gutenberg 6.2.0 released this morning.
Confirmed that this issue is resolved.
Safe to close this issue.

**Comment by alexjpanagis** [comment]
I believe this issue hasn't been resolved as I'm still experiencing it as documented in the following issue: 

https://github.com/themebeans/tabor/issues/14

Let me know if I would be able to help out by sharing additional info. Seems to be exactly as described here, but the issue just started popping up again all of a sudden.
